pref("ponify.first_run", true);
pref("ponify.ponify_enabled", true);
pref("ponify.wlist_type", 0);
pref("ponify.highlight", false);
pref("ponify.highlight_colour", "#0700FF");
pref("ponify.tooltips", false);
pref("ponify.pseudo_threading", false);
pref("ponify.replace", "[[\"confound those dover boys\",\"confound these ponies\"],[\"philadelphia\",\"fillydelphia\"],[\"sure as hell\",\"sure as hay\"],[\"no one else\",\"no pony else\"],[\"girlfriends\",\"fillyfriends\"],[\"doctor who\",\"doctor whooves\"],[\"stalingrad\",\"stalliongrad\"],[\"girlfriend\",\"fillyfriend\"],[\"nottingham\",\"trottingham\"],[\"boyfriends\",\"coltfriends\"],[\"old-timer\",\"old-trotter\"],[\"everybody\",\"everypony\"],[\"gentlemen\",\"gentlecolts\"],[\"manhattan\",\"manehattan\"],[\"trollable\",\"paraspritable\"],[\"high-five\",\"hoof-five\"],[\"boyfriend\",\"coltfriend\"],[\"halloween\",\"nightmare night\"],[\"gentleman\",\"gentlecolt\"],[\"the heck\",\"the hay\"],[\"the hell\",\"the hay\"],[\"bro-fist\",\"bro-hoof\"],[\"handedly\",\"hoofedly\"],[\"naysayer\",\"neighsayer\"],[\"butthurt\",\"flankhurt\"],[\"everyone\",\"everypony\"],[\"handmade\",\"hoofmade\"],[\"trolling\",\"paraspriting\"],[\"miracles\",\"mareacles\"],[\"somebody\",\"somepony\"],[\"bro fist\",\"bro hoof\"],[\"marathon\",\"mareathon\"],[\"children\",\"foals\"],[\"butthurt\",\"saddle-sore\"],[\"someone\",\"somepony\"],[\"america\",\"amareica\"],[\"brofist\",\"brohoof\"],[\"cowgirl\",\"cowpony\"],[\"miracle\",\"mareacle\"],[\"foolish\",\"foalish\"],[\"dr. who\",\"dr. whooves\"],[\"trolled\",\"parasprited\"],[\"anybody\",\"anypony\"],[\"persons\",\"ponies\"],[\"handers\",\"hoofers\"],[\"ladies\",\"fillies\"],[\"dr who\",\"dr whooves\"],[\"trolls\",\"parasprites\"],[\"people\",\"ponies\"],[\"tattoo\",\"cutie mark\"],[\"cowboy\",\"cowpony\"],[\"humans\",\"ponies\"],[\"person\",\"pony\"],[\"nobody\",\"nopony\"],[\"handed\",\"hoofed\"],[\"anyone\",\"anypony\"],[\"woman\",\"mare\"],[\"boner\",\"wingboner\"],[\"troll\",\"parasprite\"],[\"human\",\"pony\"],[\"hands\",\"hooves\"],[\"folks\",\"foalks\"],[\"child\",\"foal\"],[\"money\",\"bits\"],[\"women\",\"mares\"],[\"girls\",\"fillies\"],[\"girl\",\"filly\"],[\"main\",\"mane\"],[\"fool\",\"foal\"],[\"feet\",\"hooves\"],[\"hand\",\"hoof\"],[\"foot\",\"hoof\"],[\"boys\",\"colts\"],[\"boy\",\"colt\"],[\"fap\",\"clop\"],[\"man\",\"stallion\"],[\"men\",\"stallions\"],[\"hey\",\"hay\"]]");
pref("ponify.websites", "[]");
